### PR TITLE
Update to newer Minitest API to remove deprecation warnings

### PR DESCRIPTION
**Pull request by pond**
Was working on something else, and the storm of deprecation messages during test runs was triggering me :joy:

### CODE REVIEW

**Comment by pond** [comment]
The test suite seems to have some flickering issues - across the Travis matrix, one single entry failed; re-running CI. Since I have no direct access for it, I'll close and reopen the PR instead.

**Comment by pond** [comment]
Flickering test resolved itself on rerun, CI now green.

**Comment by seuros** [comment]
@pond Thanks for your contributions. 
I think the assertion syntax is clearer than using `_()`
`_(Tag.current_advisory_lock).must_be_nil` is less readable then `assert_nil Tag.current_advisory_lock`

I already have these change in a branch locally. But you can update your PR and i will merge this PR instead. 

Thanks.

**Comment by pond** [comment]
#644668e changes to the `assert`/`refute` syntax, with parentheses and parameter ordering that follows https://minitest.rubystyle.guide. I don't have everything set up locally to run all tests for all databases, so I'll let Travis run through and then see if there's anything I need to fix up afterwards.

**Review by seuros — APPROVED** [review]

**Comment by seuros** [comment]
Thank you

**Pull request merged**
